"""user details

Revision ID: 20bbb5c1b674
Revises: bdb20c13878b
Create Date: 2017-03-06 12:56:20.762542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bbb5c1b674'
down_revision = 'bdb20c13878b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('location', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
